[env:adafruit_feather_m0_express]
platform = atmelsam
board = adafruit_feather_m0_express
framework = arduino

monitor_speed = 115200

; PlatformIO normally detects the USB port automatically.
; If it does not, uncomment these and change COM3 if necessary:
; upload_port = COM3
; monitor_port = COM3
